export interface Place {
  id: string;
  name: string;
  nameZh: string;
  description: string;
  tip: string;
  cost: string;
  duration: string;
  mapUrl: string;
  lat: number;
  lng: number;
  category: "landmark" | "nature" | "food" | "transport" | "shopping" | "culture";
  tags: string[];
}

export interface Activity {
  time: string;
  title: string;
  titleZh: string;
  description: string;
  place?: Place;
  type: "travel" | "visit" | "eat" | "rest" | "accommodation";
  cost?: string;
  tip?: string;
}

export interface Day {
  id: number;
  date: string;
  title: string;
  subtitle: string;
  emoji: string;
  focus: string;
  fatigue: "LOW" | "MODERATE" | "HIGH";
  color: string;
  activities: Activity[];
  dailyBudget: string;
  highlights: string[];
}

export const itinerary: Day[] = [
  {
    id: 1,
    date: "Day 1",
    title: "Arrival + Taipei Orientation",
    subtitle: "Touch down, get grounded",
    emoji: "✈️",
    focus: "Arrival & Light Exploration",
    fatigue: "LOW",
    color: "#C41E3A",
    dailyBudget: "₱1,500–2,500",
    highlights: ["Ximending", "Shilin Night Market", "EasyCard"],
    activities: [
      {
        time: "Afternoon",
        title: "Land at Taoyuan International Airport",
        titleZh: "桃園國際機場",
        description: "Clear immigration, collect baggage, and get your bearings. Head straight to the MRT info desk.",
        type: "travel",
        cost: "Free",
        tip: "Get your EasyCard here at the airport MRT station — saves time later.",
        place: {
          id: "taoyuan-airport",
          name: "Taoyuan International Airport",
          nameZh: "桃園國際機場",
          description: "Taiwan's main international gateway, one of Asia's most efficient airports.",
          tip: "MRT Airport Express connects directly to central Taipei in ~35 minutes.",
          cost: "MRT: ~₱200",
          duration: "35–45 min to Taipei",
          mapUrl: "https://maps.google.com/?q=Taoyuan+International+Airport",
          lat: 25.0777,
          lng: 121.2328,
          category: "transport",
          tags: ["airport", "arrival", "MRT"],
        },
      },
      {
        time: "Late Afternoon",
        title: "Buy EasyCard & MRT to Ximending",
        titleZh: "悠遊卡 + 西門町",
        description: "Purchase your EasyCard (NT$100 deposit + load NT$300–500). Take MRT directly to Ximen Station.",
        type: "travel",
        cost: "~₱200",
        tip: "EasyCard works on MRT, buses, convenience stores, and even some restaurants.",
      },
      {
        time: "Evening",
        title: "Check-in – Ximending Hostel",
        titleZh: "西門町住宿",
        description: "Drop bags, freshen up. You're staying in the heart of Taipei's youth culture district.",
        type: "accommodation",
        cost: "₱800–1,500/night",
        tip: "Book ahead! Popular budget areas fill fast. Look for hostels near Ximen MRT Exit 6.",
        place: {
          id: "ximending",
          name: "Ximending",
          nameZh: "西門町",
          description: "Taipei's vibrant pedestrian shopping and entertainment district — think Tokyo's Harajuku mixed with NYC's Times Square.",
          tip: "Everything is walkable here. Explore the alleys at night for hidden gems.",
          cost: "Free to explore",
          duration: "2–3 hours",
          mapUrl: "https://maps.google.com/?q=Ximending+Taipei",
          lat: 25.0426,
          lng: 121.5076,
          category: "shopping",
          tags: ["nightlife", "shopping", "food", "walkable"],
        },
      },
      {
        time: "Night",
        title: "Shilin Night Market",
        titleZh: "士林夜市",
        description: "Taiwan's most famous night market. Try stinky tofu, oyster vermicelli, scallion pancakes, and bubble tea. Sensory overload in the best way.",
        type: "eat",
        cost: "₱200–400",
        tip: "Arrive by 8PM for the best selection. Oyster omelette (蚵仔煎) and XXL Crispy Chicken are must-tries.",
        place: {
          id: "shilin-night-market",
          name: "Shilin Night Market",
          nameZh: "士林夜市",
          description: "Taipei's largest and most famous night market. A culinary adventure spanning hundreds of stalls.",
          tip: "Take MRT to Jiantan Station (Red Line). Market is 5 min walk.",
          cost: "₱200–500 per person",
          duration: "2–3 hours",
          mapUrl: "https://maps.google.com/?q=Shilin+Night+Market",
          lat: 25.0881,
          lng: 121.5245,
          category: "food",
          tags: ["night market", "street food", "must-visit"],
        },
      },
    ],
  },
  {
    id: 2,
    date: "Day 2",
    title: "Taipei City + Culture",
    subtitle: "Urban landmarks & skyline views",
    emoji: "🏙️",
    focus: "Urban Landmarks via MRT",
    fatigue: "MODERATE",
    color: "#2D6A4F",
    dailyBudget: "₱1,200–2,000",
    highlights: ["Taipei 101", "CKS Memorial", "Elephant Mountain"],
    activities: [
      {
        time: "Morning (9AM)",
        title: "Chiang Kai-shek Memorial Hall",
        titleZh: "中正紀念堂",
        description: "Iconic white marble monument with the changing of the guard ceremony. Surrounding Liberty Square is stunning. Free entry.",
        type: "visit",
        cost: "Free",
        tip: "Changing of the guard happens every hour on the hour. The 9AM ceremony is less crowded.",
        place: {
          id: "cks-memorial",
          name: "Chiang Kai-shek Memorial Hall",
          nameZh: "中正紀念堂",
          description: "One of Taiwan's most iconic landmarks, this white marble hall honors the former president. The surrounding Liberty Square and National Theater make it a cultural centerpiece.",
          tip: "MRT: Chiang Kai-shek Memorial Hall Station (Blue Line). Free entry!",
          cost: "Free",
          duration: "1–1.5 hours",
          mapUrl: "https://maps.google.com/?q=Chiang+Kai-shek+Memorial+Hall",
          lat: 25.0340,
          lng: 121.5220,
          category: "culture",
          tags: ["history", "architecture", "free", "landmark"],
        },
      },
      {
        time: "Mid-Morning (11AM)",
        title: "Taipei 101 Observatory (Optional)",
        titleZh: "台北101觀景台",
        description: "The world's 2nd tallest building until 2010. The indoor observatory at 89F gives jaw-dropping 360° views of Taipei.",
        type: "visit",
        cost: "₱800–1,000 (NT$600)",
        tip: "Go on a clear day for mountain views. Weekday mornings have shortest queues.",
        place: {
          id: "taipei-101",
          name: "Taipei 101",
          nameZh: "台北101",
          description: "A supertall skyscraper that was once the world's tallest building. The shopping mall below is free; the observatory requires a ticket.",
          tip: "The outdoor observatory on 91F is spectacular but windier. Book tickets online to skip queues.",
          cost: "NT$600 (~₱1,000) observatory",
          duration: "1–2 hours",
          mapUrl: "https://maps.google.com/?q=Taipei+101",
          lat: 25.0330,
          lng: 121.5654,
          category: "landmark",
          tags: ["skyline", "architecture", "views", "iconic"],
        },
      },
      {
        time: "Afternoon (2PM)",
        title: "Elephant Mountain Hike",
        titleZh: "象山步道",
        description: "A 20-minute hike up stone steps rewards you with the most photographed view of Taipei — Taipei 101 framed against the city skyline.",
        type: "visit",
        cost: "Free",
        tip: "Wear grippy shoes. The climb takes 20 mins up. Best at sunset (around 6PM) but afternoon is less crowded.",
        place: {
          id: "elephant-mountain",
          name: "Elephant Mountain",
          nameZh: "象山",
          description: "A short but rewarding hike offering iconic views of Taipei 101 and the city skyline. One of Taipei's most popular viewpoints.",
          tip: "MRT: Xiangshan Station, then 15-min walk to trailhead. Free entry.",
          cost: "Free",
          duration: "1–1.5 hours round trip",
          mapUrl: "https://maps.google.com/?q=Elephant+Mountain+Taipei",
          lat: 25.0283,
          lng: 121.5771,
          category: "nature",
          tags: ["hike", "views", "free", "photography"],
        },
      },
      {
        time: "Evening",
        title: "Raohe Street Night Market",
        titleZh: "饒河街夜市",
        description: "One of Taipei's oldest night markets. More local than Shilin, with legendary pepper pork buns from the temple stall.",
        type: "eat",
        cost: "₱200–400",
        tip: "The black pepper buns (胡椒餅) from the stall at the temple entrance are worth the queue.",
        place: {
          id: "raohe-night-market",
          name: "Raohe Street Night Market",
          nameZh: "饒河街夜市",
          description: "A 600-meter-long night market street, one of Taipei's oldest. Famous for the black pepper buns (胡椒餅).",
          tip: "MRT: Songshan Station. Opens around 5PM.",
          cost: "₱200–400",
          duration: "1.5 hours",
          mapUrl: "https://maps.google.com/?q=Raohe+Street+Night+Market",
          lat: 25.0505,
          lng: 121.5773,
          category: "food",
          tags: ["night market", "street food", "local"],
        },
      },
    ],
  },
  {
    id: 3,
    date: "Day 3",
    title: "Beitou + Chung Cheng University",
    subtitle: "Hot springs, nature & campus beauty",
    emoji: "🌿",
    focus: "Nature, Recovery & Academia",
    fatigue: "LOW",
    color: "#C9A84C",
    dailyBudget: "₱800–1,500",
    highlights: ["Beitou Hot Springs", "Thermal Valley", "NCCU Campus"],
    activities: [
      {
        time: "Morning (9AM)",
        title: "Beitou Thermal Valley (Diyu Gu)",
        titleZh: "地熱谷",
        description: "A jade-green, naturally boiling hot spring lake nicknamed 'Hell Valley' by locals. Ethereal mist rises from the 100°C water. One of Taipei's most otherworldly sights.",
        type: "visit",
        cost: "Free",
        tip: "Go early — opens at 9AM and fills up quickly. The teal water is due to radium-rich minerals.",
        place: {
          id: "beitou-thermal-valley",
          name: "Beitou Thermal Valley",
          nameZh: "地熱谷",
          description: "A naturally boiling emerald lake shrouded in mist. The water reaches nearly 100°C, containing rare radium minerals that give it a stunning jade-green hue.",
          tip: "MRT: Xinbeitou Station, then bus or 20-min walk uphill.",
          cost: "Free",
          duration: "45 minutes",
          mapUrl: "https://maps.google.com/?q=Beitou+Thermal+Valley",
          lat: 25.1384,
          lng: 121.5098,
          category: "nature",
          tags: ["hot spring", "nature", "free", "unique"],
        },
      },
      {
        time: "Late Morning (11AM)",
        title: "Beitou Hot Springs Soak",
        titleZh: "北投溫泉",
        description: "Beitou has public and private hot spring baths. Choose a public bath for budget-friendly relaxation (NT$100–200) or splurge on a private room for ultimate recovery.",
        type: "rest",
        cost: "₱180–600 (NT$100–400)",
        tip: "Public baths are gender-separated and swimwear is mandatory. Private rooms need booking ahead.",
        place: {
          id: "beitou-hot-springs",
          name: "Beitou Hot Springs",
          nameZh: "北投溫泉",
          description: "A historical hot spring resort area just 30 minutes from central Taipei. The sulfuric springs here have been renowned since Japanese colonial rule.",
          tip: "Millennium Hot Spring (公共浴室) is the best budget option at NT$100. Bring your own towel.",
          cost: "₱180–600",
          duration: "1–2 hours",
          mapUrl: "https://maps.google.com/?q=Beitou+Hot+Springs",
          lat: 25.1374,
          lng: 121.5061,
          category: "nature",
          tags: ["wellness", "hot spring", "relaxation", "recovery"],
        },
      },
      {
        time: "Afternoon (2PM)",
        title: "Beitou Public Library",
        titleZh: "北投圖書館",
        description: "Taiwan's first green building and one of the most beautiful libraries in Asia. A stunning wooden structure built over a pond surrounded by forest. Architecture lovers, this is unmissable.",
        type: "visit",
        cost: "Free",
        tip: "The library is small so visits are timed (30-min limit during peak hours). Just enjoying the exterior and pond is worth the trip.",
        place: {
          id: "beitou-library",
          name: "Beitou Public Library",
          nameZh: "北投圖書館",
          description: "An award-winning eco-friendly library built with reclaimed wood, solar panels, and a living roof. One of the top 25 most beautiful libraries in the world.",
          tip: "Go on weekdays if you want to browse inside. The forest trail beside it is lovely.",
          cost: "Free",
          duration: "30–45 minutes",
          mapUrl: "https://maps.google.com/?q=Beitou+Public+Library",
          lat: 25.1368,
          lng: 121.5048,
          category: "culture",
          tags: ["architecture", "library", "green building", "free"],
        },
      },
      {
        time: "Late Afternoon (4PM)",
        title: "National Chung Cheng University",
        titleZh: "國立中正大學",
        description: "Travel south to Chiayi to visit NCCU's stunning campus. Set against the scenic foothills with beautiful landscaping, koi ponds, and Taiwanese architecture. The campus lake and surrounding mountains are photogenic at golden hour.",
        type: "visit",
        cost: "Free",
        tip: "NCCU's campus is massive and scenic. Walk to Liyutan Lake on campus for reflective mountain views. The university is a 35-min drive from Chiayi Station.",
        place: {
          id: "nccu",
          name: "National Chung Cheng University",
          nameZh: "國立中正大學",
          description: "A prestigious national research university in Minxiong Township, Chiayi. The campus is set against the scenic Alishan foothills with lush greenery, serene lakes, and striking architecture.",
          tip: "Liyutan Lake (鱸鰻潭) near campus is stunning at sunset. The campus deer park is a hidden gem.",
          cost: "Free",
          duration: "1.5–2 hours",
          mapUrl: "https://maps.google.com/?q=National+Chung+Cheng+University+Chiayi",
          lat: 23.5979,
          lng: 120.4739,
          category: "culture",
          tags: ["university", "campus", "nature", "photography", "Chiayi"],
        },
      },
      {
        time: "Evening",
        title: "Chiayi Night Market Dinner",
        titleZh: "嘉義夜市",
        description: "Chiayi is famous for its turkey rice (火雞肉飯) — a uniquely local dish not found elsewhere in Taiwan. This is authentic southern Taiwan cuisine.",
        type: "eat",
        cost: "₱150–250",
        tip: "Try 'Fong Cheng Turkey Rice' near the train station. NT$35–60 a bowl — absurdly cheap and delicious.",
        place: {
          id: "chiayi-night-market",
          name: "Chiayi Night Market & Turkey Rice",
          nameZh: "嘉義夜市 & 火雞肉飯",
          description: "Chiayi's vibrant night market and its signature turkey rice. The city is a culinary treasure off the main tourist trail.",
          tip: "The night market near Chiayi City Hall has good variety. Don't leave without trying at least two bowls of turkey rice.",
          cost: "₱150–300",
          duration: "1.5 hours",
          mapUrl: "https://maps.google.com/?q=Chiayi+Night+Market",
          lat: 23.4801,
          lng: 120.4491,
          category: "food",
          tags: ["night market", "turkey rice", "local cuisine", "Chiayi"],
        },
      },
    ],
  },
  {
    id: 4,
    date: "Day 4",
    title: "The Northeast Coast Day Trip",
    subtitle: "Taiwan's most scenic countryside loop",
    emoji: "🌄",
    focus: "Rural Taiwan – Maximum Exposure Per Cost",
    fatigue: "MODERATE",
    color: "#4A5568",
    dailyBudget: "₱2,000–3,500",
    highlights: ["Yehliu", "Jiufen", "Shifen Waterfall"],
    activities: [
      {
        time: "Morning (8AM)",
        title: "Join Shared Day Tour",
        titleZh: "一日遊行程",
        description: "Book a shared northeast coast day tour from your hostel or Klook. This covers all 4 stops efficiently and includes transport — DIY is slower and more expensive for this route.",
        type: "travel",
        cost: "₱1,500–2,200",
        tip: "Book via Klook or KKday the night before. Tours depart from Taipei Main Station or Ximending.",
      },
      {
        time: "Morning (9AM)",
        title: "Yehliu Geopark",
        titleZh: "野柳地質公園",
        description: "A geological wonderland jutting into the Pacific Ocean. Famous for the iconic 'Queen's Head' mushroom rock and hundreds of other wind-sculpted formations. Like a lunar landscape on Earth.",
        type: "visit",
        cost: "₱180 (NT$120)",
        tip: "The Queen's Head has a long photo queue. Get there early (first stop on most tours) or ask your guide to take your shot while others wait.",
        place: {
          id: "yehliu",
          name: "Yehliu Geopark",
          nameZh: "野柳地質公園",
          description: "A dramatic coastal cape with over 180 types of wind and wave-sculpted rock formations. The Queen's Head rock is the most photographed formation in Taiwan.",
          tip: "Stay on marked paths — erosion fines are serious. Morning light (9–10AM) is best for photography.",
          cost: "NT$120 (~₱180)",
          duration: "1–1.5 hours",
          mapUrl: "https://maps.google.com/?q=Yehliu+Geopark",
          lat: 25.2038,
          lng: 121.6893,
          category: "nature",
          tags: ["geology", "coastal", "photography", "unique"],
        },
      },
      {
        time: "Late Morning (11AM)",
        title: "Shifen Waterfall & Old Street",
        titleZh: "十分瀑布 & 十分老街",
        description: "Taiwan's widest waterfall, nicknamed 'Little Niagara.' Release a sky lantern on the historic old street — a bucket list Taiwan experience. Write your wishes, light it, and watch it drift away.",
        type: "visit",
        cost: "₱500–700",
        tip: "The waterfall entrance is NT$80. Sky lanterns cost NT$150–200 each. The train track photo on the old street is a must — trains run every 30 mins so time it right!",
        place: {
          id: "shifen",
          name: "Shifen Waterfall & Old Street",
          nameZh: "十分瀑布 & 十分老街",
          description: "Shifen Waterfall is the widest in Taiwan at 40 meters. The adjacent Old Street runs along an active train track where tourists release sky lanterns with wishes written on them.",
          tip: "The waterfall is a 20-min walk from the Old Street. Comfortable shoes required. Go to the waterfall first, lantern after.",
          cost: "NT$80 + NT$150–200 lantern",
          duration: "1.5–2 hours",
          mapUrl: "https://maps.google.com/?q=Shifen+Waterfall",
          lat: 25.0490,
          lng: 121.7808,
          category: "nature",
          tags: ["waterfall", "sky lantern", "bucketlist", "old street"],
        },
      },
      {
        time: "Afternoon (2PM)",
        title: "Jiufen Old Street",
        titleZh: "九份老街",
        description: "The hilltop village that inspired Studio Ghibli's Spirited Away (rumored). Narrow red-lantern-lit alleyways, teahouses overlooking the Pacific, and misty mountain views. Magical.",
        type: "visit",
        cost: "₱300–600",
        tip: "The iconic lantern-lit staircase shot is best at dusk (5–6PM). If your tour allows, ask to stay for sunset at A-Mei Teahouse.",
        place: {
          id: "jiufen",
          name: "Jiufen Old Street",
          nameZh: "九份老街",
          description: "A hillside gold mining village turned atmospheric destination. Winding lanes, red lanterns, traditional tea houses, and sweeping views of the Pacific make Jiufen one of Taiwan's most enchanting spots.",
          tip: "Jiufen taro balls (芋圓) are the local specialty. Eat them overlooking the sea at any teahouse terrace.",
          cost: "₱300–600 food + tea",
          duration: "2–3 hours",
          mapUrl: "https://maps.google.com/?q=Jiufen+Old+Street",
          lat: 25.1089,
          lng: 121.8441,
          category: "culture",
          tags: ["old town", "lanterns", "teahouse", "photography", "iconic"],
        },
      },
      {
        time: "Evening",
        title: "Return to Taipei",
        titleZh: "返回台北",
        description: "Tour drops you back in Taipei by 7–8PM. Grab convenience store dinner (7-Eleven Taiwan is genuinely elite — hot food, fresh bento, amazing coffee) or a quick bowl at a noodle shop.",
        type: "travel",
        cost: "₱50–150",
        tip: "7-Eleven's City Café coffee and 茶葉蛋 (tea eggs) are a rightful Taiwanese institution. Don't skip them.",
      },
    ],
  },
  {
    id: 5,
    date: "Day 5",
    title: "Chill, Pasalubong & Departure",
    subtitle: "Tea gondola or shopping — your call",
    emoji: "🌿",
    focus: "Light + Buffer Day",
    fatigue: "LOW",
    color: "#2D6A4F",
    dailyBudget: "₱1,000–2,500",
    highlights: ["Maokong Gondola", "Pasalubong Shopping", "Airport"],
    activities: [
      {
        time: "Morning (9AM)",
        title: "Option A: Maokong Gondola",
        titleZh: "貓空纜車",
        description: "A 20-minute cable car ride above a forested mountain ending at Maokong — Taipei's tea-growing region. Sip oolong with a view of the entire city below. Incredibly peaceful.",
        type: "visit",
        cost: "₱200–300 (NT$120 round trip)",
        tip: "Take the crystal cabin (glass floor) for NT$50 extra — worth every peso. Opens at 9AM on weekdays.",
        place: {
          id: "maokong-gondola",
          name: "Maokong Gondola",
          nameZh: "貓空纜車",
          description: "A scenic cable car connecting Taipei Zoo to Maokong mountain. The ride passes over forested hills and offers aerial views of the city. At the top, tea farms and teahouses await.",
          tip: "Book crystal cabin online. Ride is 30-40 min one way. Combine with a stroll and tea break at the top.",
          cost: "NT$120 round trip (~₱200)",
          duration: "2–3 hours",
          mapUrl: "https://maps.google.com/?q=Maokong+Gondola",
          lat: 24.9598,
          lng: 121.5831,
          category: "nature",
          tags: ["gondola", "tea", "views", "peaceful"],
        },
      },
      {
        time: "Morning (9AM)",
        title: "Option B: Pasalubong Shopping",
        titleZh: "伴手禮購物",
        description: "Ximending and nearby Zhongshan have great souvenir options. Must-buys: pineapple cakes (鳳梨酥), Hi-Chew candy, Sun Cakes, Taiwan whisky miniatures, bubble tea kits, and Kavalan chocolates.",
        type: "visit",
        cost: "Variable",
        tip: "Sunflower and SunnyHills brand pineapple cakes are top tier. Get extras — they disappear fast at home.",
        place: {
          id: "souvenir-shopping",
          name: "Ximending Souvenir District",
          nameZh: "西門町伴手禮",
          description: "Ximending and the surrounding area has excellent souvenir shops alongside department stores for last-minute gifts.",
          tip: "Breeze Center and Shin Kong Mitsukoshi have curated Taiwan specialty gift floors. Budget 2–3 hours.",
          cost: "Variable",
          duration: "2–3 hours",
          mapUrl: "https://maps.google.com/?q=Ximending+Taipei",
          lat: 25.0426,
          lng: 121.5076,
          category: "shopping",
          tags: ["souvenirs", "pasalubong", "pineapple cake", "shopping"],
        },
      },
      {
        time: "Afternoon (2PM)",
        title: "Lunch & Check-Out",
        titleZh: "午餐 & 退房",
        description: "Final proper Taiwanese meal — beef noodle soup (牛肉麵) is the move. Then pack up and head to the airport with buffer time.",
        type: "eat",
        cost: "₱200–400",
        tip: "Lin Dong Fang Beef Noodle near Zhongxiao Dunhua is legendary. Queue expected but worth it.",
      },
      {
        time: "Late Afternoon",
        title: "Airport Transfer & Departure",
        titleZh: "機場送機",
        description: "Take the Airport MRT from Taipei Main Station. Journey is ~35 minutes. Check-in 2–3 hours before your flight. Until next time, Taiwan! 再見！",
        type: "travel",
        cost: "₱200",
        tip: "The Airport MRT has dedicated luggage storage areas. Extremely smooth and fast.",
        place: {
          id: "departure",
          name: "Taoyuan Airport – Departure",
          nameZh: "桃園機場出發",
          description: "Taoyuan's modern terminals with excellent duty-free shopping. Final chance for Taiwan snacks and whisky.",
          tip: "Duty-free has Kavalan Whisky at great prices. Pick up pineapple cake boxes in the terminal too.",
          cost: "MRT: ~₱200",
          duration: "35 min to airport",
          mapUrl: "https://maps.google.com/?q=Taoyuan+International+Airport",
          lat: 25.0777,
          lng: 121.2328,
          category: "transport",
          tags: ["airport", "departure", "duty-free"],
        },
      },
    ],
  },
];

export const tripSummary = {
  title: "Taiwan 2027",
  subtitle: "5 Days · Taipei + Chiayi · Budget Optimized",
  totalDays: 5,
  startDate: "TBD 2027",
  endDate: "TBD 2027",
  totalBudget: "₱15,000–25,000",
  travelers: "Group",
  baseCity: "Taipei (Ximending)",
  transportCard: "EasyCard",
  heroTagline: "五天台灣之旅",
  stats: [
    { label: "Days", value: "5", unit: "" },
    { label: "Places", value: "15+", unit: "" },
    { label: "Daily Budget", value: "₱800–3K", unit: "" },
    { label: "MRT Cost", value: "₱150", unit: "/day" },
  ],
};
